// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wijcokzhidfimwnywsuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpamNva3poaWRmaW13bnl3c3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDk0OTIsImV4cCI6MjA2NjA4NTQ5Mn0.HOl9D1i5z_bpgsdL0baDaqbbeXS-uKl8PKq3CwH6LUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);